/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    institutions: Institution;
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    votes: Vote;
    'page-views': PageView;
    'admin-logs': AdminLog;
    comments: Comment;
    feedback: Feedback;
    templates: Template;
    'newsletter-subscribers': NewsletterSubscriber;
    newsletters: Newsletter;
    'newsletter-events': NewsletterEvent;
    events: Event;
    clubs: Club;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    institutions: InstitutionsSelect<false> | InstitutionsSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    votes: VotesSelect<false> | VotesSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    'admin-logs': AdminLogsSelect<false> | AdminLogsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    'newsletter-events': NewsletterEventsSelect<false> | NewsletterEventsSelect<true>;
    events: EventsSelect<false> | EventsSelect<true>;
    clubs: ClubsSelect<false> | ClubsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: {
      'newsletter-daily-digest': TaskNewsletterDailyDigest;
      'newsletter-weekly-digest': TaskNewsletterWeeklyDigest;
      'newsletter-monthly-digest': TaskNewsletterMonthlyDigest;
      'newsletter-scheduled-send': TaskNewsletterScheduledSend;
      'newsletter-stats-rollup': TaskNewsletterStatsRollup;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Manage institutions (colleges) on the platform
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions".
 */
export interface Institution {
  id: string;
  /**
   * Full institution name (e.g., "G H Patel College of Engineering and Technology")
   */
  name: string;
  /**
   * Short code used in URLs, API routing, and data isolation (e.g., "gcet")
   */
  code: string;
  /**
   * Short display name (e.g., "GCET")
   */
  shortName?: string | null;
  /**
   * Institution logo
   */
  logo?: (string | null) | Media;
  /**
   * Custom domains mapped to this institution. College IT adds CNAME → your platform.
   */
  domains?:
    | {
        /**
         * Full hostname (e.g., "blog.gcet.edu.in", "ieee.gcet.edu.in")
         */
        hostname: string;
        /**
         * What this domain is for — determines content filtering and routing behavior
         */
        purpose: 'main' | 'blog' | 'club' | 'department';
        /**
         * Club slug or department code (only for club/department domains)
         */
        scopeId?: string | null;
        /**
         * Has DNS/CNAME been verified? (auto-set by verification check)
         */
        verified?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Institution lifecycle status
   */
  status: 'active' | 'trial' | 'suspended';
  /**
   * Subscription tier — determines available features
   */
  tier: 'pilot' | 'standard' | 'premium';
  /**
   * Institution contact information
   */
  contact?: {
    /**
     * Primary contact email
     */
    email?: string | null;
    /**
     * Contact phone number
     */
    phone?: string | null;
    /**
     * Official institution website
     */
    website?: string | null;
    /**
     * Physical address
     */
    address?: string | null;
  };
  /**
   * Institution-level settings
   */
  settings?: {
    /**
     * Which platform modules are enabled for this institution
     */
    enabledModules?: ('blog' | 'events' | 'clubs' | 'gallery' | 'newsletter' | 'conosco')[] | null;
    /**
     * Maximum users allowed (0 = unlimited)
     */
    maxUsers?: number | null;
    /**
     * Conosco ERP institution code for API integration
     */
    conoscoInstitutionCode?: string | null;
    /**
     * Per-institution Conosco API endpoint (e.g., https://api.conosco.in/v1)
     */
    conoscoApiUrl?: string | null;
  };
  /**
   * Visual branding applied across this institution's site
   */
  branding?: {
    /**
     * Primary brand color (hex, e.g., #1a5276)
     */
    primaryColor?: string | null;
    /**
     * Accent/secondary color (hex)
     */
    accentColor?: string | null;
    /**
     * Institution tagline (appears in hero, footer, etc.)
     */
    tagline?: string | null;
    /**
     * Custom favicon for this institution's site
     */
    favicon?: (string | null) | Media;
  };
  /**
   * Navigation items for this institution's header. Falls back to global Header if empty.
   */
  headerNavItems?:
    | {
        label: string;
        /**
         * Relative URL (e.g., /events) or absolute URL
         */
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Footer links for this institution. Falls back to global Footer if empty.
   */
  footerNavItems?:
    | {
        label: string;
        url: string;
        newTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Custom footer text (copyright, disclaimer, etc.)
   */
  footerText?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📸 Recommended sizes: Hero 1920×1080 (16:9), Cards 900×600 (3:2), OG 1200×630. Optimize images to <500KB. See IMAGE_GUIDELINES.md for details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  alt?: string | null;
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Cloudinary CDN URL for the uploaded image
   */
  cloudinaryUrl?: string | null;
  /**
   * What type of content this media is associated with
   */
  contextType?: ('post' | 'event' | 'club' | 'page' | 'general') | null;
  /**
   * ID of the associated content item
   */
  contextId?: string | null;
  /**
   * User who uploaded this media
   */
  uploadedBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * Which institution this user belongs to. SuperAdmins have no institution.
   */
  institution?: (string | null) | Institution;
  /**
   * Base role. SuperAdmin = platform owner. User = institution member with role assignments.
   */
  role?: ('user' | 'superadmin') | null;
  /**
   * Assigned roles with scope. institution_admin can assign roles within their institution. SuperAdmin can assign any role.
   */
  roleAssignments?:
    | {
        assignedRole:
          | 'institution_admin'
          | 'club_admin'
          | 'club_editor'
          | 'blog_editor'
          | 'blog_author'
          | 'event_manager'
          | 'moderator';
        scopeType: 'institution' | 'club' | 'blog' | 'global';
        /**
         * Which club or institution this role applies to. Required for club and institution scopes.
         */
        scopeId?:
          | ({
              relationTo: 'clubs';
              value: string | Club;
            } | null)
          | ({
              relationTo: 'institutions';
              value: string | Institution;
            } | null);
        /**
         * Auto-populated display label (e.g., "Coding Club", "GCET")
         */
        scopeLabel?: string | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Short bio for author pages
   */
  bio?: string | null;
  avatar?: (string | null) | Media;
  /**
   * Department or branch (e.g., CSE, ECE, ME)
   */
  department?: string | null;
  /**
   * Year of study or designation
   */
  year?: string | null;
  /**
   * How the user authenticates (managed automatically)
   */
  authProvider?: ('local' | 'google' | 'both') | null;
  /**
   * Google account unique ID (set automatically on Google sign-in)
   */
  googleSubId?: string | null;
  /**
   * Social media profiles
   */
  socialLinks?: {
    /**
     * Twitter/X profile URL
     */
    twitter?: string | null;
    /**
     * LinkedIn profile URL
     */
    linkedin?: string | null;
    /**
     * GitHub profile URL
     */
    github?: string | null;
    /**
     * Personal website URL
     */
    website?: string | null;
  };
  /**
   * Opt-in to receive the newsletter
   */
  newsletterOptIn?: boolean | null;
  /**
   * How often you want to receive newsletters
   */
  newsletterFrequency?: ('daily' | 'weekly' | 'monthly') | null;
  /**
   * Only receive newsletters about these categories (leave empty for all)
   */
  newsletterCategories?: (string | Category)[] | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * 🏛️ Clubs & societies from Conosco API or manually created. CMS adds SEO, images, and editorial content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs".
 */
export interface Club {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  title: string;
  /**
   * Club banner/hero image (overrides Conosco logo for display)
   */
  heroImage?: (string | null) | Media;
  /**
   * Club logo (used in cards and listings)
   */
  logo?: (string | null) | Media;
  /**
   * Rich editorial content about the club. Conosco description is shown separately.
   */
  editorialDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Club classification. For Conosco clubs, this mirrors the API value.
   */
  classification?: ('technical' | 'cultural' | 'sports' | 'social' | 'professional' | 'other') | null;
  /**
   * Affiliated department
   */
  department?: ('CSE' | 'IT' | 'ECE' | 'EE' | 'ME' | 'CE' | 'CHE' | 'AIML' | 'AIDS' | 'GENERAL') | null;
  /**
   * Status for manual clubs. Conosco clubs get status from API.
   */
  manualStatus?: ('active' | 'inactive') | null;
  /**
   * Social media links for manual clubs
   */
  socialLinks?: {
    website?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
    twitter?: string | null;
    github?: string | null;
  };
  /**
   * Where this club originates. Conosco clubs sync operational data from the API.
   */
  dataSource: 'manual' | 'conosco';
  /**
   * Semantic club code from Conosco (e.g., CLB-2025-0012). Used to link CMS record to API data.
   */
  conoscoClubCode?: string | null;
  /**
   * Last time this record was synced with Conosco API
   */
  lastSyncedAt?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Per-club visual tokens. Applied as CSS custom properties on the club landing page.
   */
  theme?: {
    /**
     * Primary brand color (hex, e.g. #0047AB)
     */
    primaryColor?: string | null;
    /**
     * Secondary accent color (hex)
     */
    accentColor?: string | null;
    /**
     * Card rendering style on the club landing page
     */
    cardStyle?: ('default' | 'glass' | 'bordered' | 'elevated') | null;
    /**
     * Font family preset for the club landing page
     */
    fontPreset?: ('default' | 'modern' | 'classic' | 'technical') | null;
  };
  /**
   * Feature this club prominently on the clubs page
   */
  featured?: boolean | null;
  /**
   * Blog posts related to this club
   */
  relatedPosts?: (string | Post)[] | null;
  /**
   * Free-form tags (comma-separated)
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  title: string;
  /**
   * Content type — affects display and routing
   */
  contentVariant?: ('blog-post' | 'news' | 'announcement' | 'event-coverage' | 'tutorial' | 'landing-page') | null;
  /**
   * Department this content belongs to
   */
  department?: ('CSE' | 'IT' | 'ECE' | 'EE' | 'ME' | 'CE' | 'CHE' | 'AIML' | 'AIDS' | 'GENERAL') | null;
  /**
   * Recommended: 1920×1080 (16:9). For portraits, keep faces in top 60% of frame. Compress to <500KB.
   */
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  /**
   * Events related to this post
   */
  relatedEvents?: (string | Event)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Free-form tags (comma-separated). E.g: tech, campus, events
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Flag this post for inclusion in the next newsletter digest
   */
  newsletterCandidate?: boolean | null;
  /**
   * Start date for featuring this post (e.g., event start)
   */
  featuredFrom?: string | null;
  /**
   * End date for featuring this post (e.g., event end)
   */
  featuredUntil?: string | null;
  /**
   * Calculated vote score (upvotes - downvotes)
   */
  voteScore?: number | null;
  /**
   * Total number of upvotes (likes)
   */
  likesCount?: number | null;
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * Feedback from editor for rejected posts
   */
  editorFeedback?: string | null;
  /**
   * Current review status of the post
   */
  reviewStatus?: ('draft' | 'pending_review' | 'approved' | 'rejected') | null;
  /**
   * When the post was submitted for review
   */
  submittedForReviewAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  title: string;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * 📅 Events from Conosco API or manually created. CMS adds SEO, images, and editorial content.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events".
 */
export interface Event {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  title: string;
  /**
   * All clubs organizing this event. Supports collaborative events (e.g., IEEE + Coding Club hackathon).
   */
  organizingClubs?: (string | Club)[] | null;
  /**
   * The primary club that created this event. Only this club's admin (or superadmin) can edit.
   */
  createdByClub?: (string | null) | Club;
  /**
   * Custom hero image (overrides Conosco poster for display)
   */
  heroImage?: (string | null) | Media;
  /**
   * Additional editorial content. Conosco description is shown separately.
   */
  editorialDescription?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * For manual events. Conosco events get this from API.
   */
  eventType?:
    | (
        | 'workshop'
        | 'seminar'
        | 'hackathon'
        | 'competition'
        | 'cultural'
        | 'sports'
        | 'guest-lecture'
        | 'conference'
        | 'webinar'
        | 'other'
      )
    | null;
  /**
   * Organizing department
   */
  department?: ('CSE' | 'IT' | 'ECE' | 'EE' | 'ME' | 'CE' | 'CHE' | 'AIML' | 'AIDS' | 'GENERAL') | null;
  /**
   * Only for manual events. Conosco events get dates from API.
   */
  startDate?: string | null;
  endDate?: string | null;
  /**
   * Venue name for manual events
   */
  venue?: string | null;
  /**
   * Status for manual events. Conosco events get status from API.
   */
  manualStatus?: ('upcoming' | 'ongoing' | 'completed' | 'cancelled') | null;
  /**
   * Where this event originates. Manual = CMS-only. Conosco = synced from ERP. External = IEEE vTools, Unstop, etc.
   */
  dataSource: 'manual' | 'conosco' | 'external';
  /**
   * External registration link (Google Form, Unstop, vTools, etc.)
   */
  registrationUrl?: string | null;
  /**
   * Which platform manages this event
   */
  externalPlatform?: ('ieee-vtools' | 'unstop' | 'eventbrite' | 'devfolio' | 'google-forms' | 'other') | null;
  /**
   * Canonical URL on the external platform
   */
  externalEventUrl?: string | null;
  /**
   * Semantic event code from Conosco (e.g., EVT-2025-0042). Used to link CMS record to API data.
   */
  conoscoEventCode?: string | null;
  /**
   * Last time this record was synced with Conosco API
   */
  lastSyncedAt?: string | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Feature this event prominently on the events page
   */
  featured?: boolean | null;
  /**
   * Blog posts related to this event
   */
  relatedPosts?: (string | Post)[] | null;
  /**
   * Free-form tags (comma-separated)
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (
    | CallToActionBlock
    | ContentBlock
    | MediaBlock
    | ArchiveBlock
    | FormBlock
    | StatsBlockType
    | EventsFeedBlockType
    | TeamGridBlockType
    | CountdownBlockType
    | GalleryPreviewBlockType
    | SponsorsBlockType
    | TestimonialsBlockType
    | ScheduleBlockType
    | ContactBlockType
  )[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  /**
   * If set, this page becomes the club landing page at /clubs/[slug]. The page blocks and hero will render as the club's custom landing page.
   */
  club?: (string | null) | Club;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockType".
 */
export interface StatsBlockType {
  /**
   * Optional heading above the stats
   */
  heading?: string | null;
  layout?: ('grid' | 'strip') | null;
  stats?:
    | {
        label: string;
        value: string;
        icon?: ('users' | 'calendar' | 'trophy' | 'star' | 'target' | 'zap') | null;
        /**
         * Optional helper text below the value
         */
        description?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'statsBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsFeedBlockType".
 */
export interface EventsFeedBlockType {
  heading?: string | null;
  /**
   * Show events for a specific club. Leave empty for all events.
   */
  club?: (string | null) | Club;
  limit?: number | null;
  layout?: ('cards' | 'timeline') | null;
  /**
   * Show event status badge (upcoming, ongoing, completed)
   */
  showStatus?: boolean | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'eventsFeed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamGridBlockType".
 */
export interface TeamGridBlockType {
  heading?: string | null;
  /**
   * Manual: define members below. Conosco: auto-loaded from club data.
   */
  source?: ('manual' | 'conosco') | null;
  layout?: ('grid' | 'compact') | null;
  /**
   * Add team members manually
   */
  members?:
    | {
        name: string;
        role: string;
        image?: (string | null) | Media;
        email?: string | null;
        /**
         * LinkedIn profile URL
         */
        linkedIn?: string | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'teamGrid';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CountdownBlockType".
 */
export interface CountdownBlockType {
  /**
   * The name of the event being counted down to
   */
  eventTitle: string;
  /**
   * Date & time the event starts
   */
  targetDate: string;
  /**
   * Optional short description shown below the title
   */
  description?: string | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'countdown';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryPreviewBlockType".
 */
export interface GalleryPreviewBlockType {
  heading?: string | null;
  images?:
    | {
        image: string | Media;
        caption?: string | null;
        id?: string | null;
      }[]
    | null;
  layout?: ('grid' | 'masonry') | null;
  /**
   * Number of images to show in the preview
   */
  limit?: number | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'galleryPreview';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorsBlockType".
 */
export interface SponsorsBlockType {
  heading?: string | null;
  layout?: ('grid' | 'marquee') | null;
  sponsors?:
    | {
        name: string;
        logo: string | Media;
        /**
         * Link to sponsor website
         */
        url?: string | null;
        tier?: ('gold' | 'silver' | 'bronze' | 'partner') | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'sponsors';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockType".
 */
export interface TestimonialsBlockType {
  heading?: string | null;
  layout?: ('grid' | 'highlight') | null;
  testimonials?:
    | {
        quote: string;
        author: string;
        /**
         * e.g. "President 2024", "Alumni 2023"
         */
        role?: string | null;
        image?: (string | null) | Media;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'testimonials';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScheduleBlockType".
 */
export interface ScheduleBlockType {
  heading?: string | null;
  days?:
    | {
        date: string;
        /**
         * e.g. "Day 1 — Opening Ceremony"
         */
        title?: string | null;
        sessions?:
          | {
              /**
               * e.g. "10:00 AM – 11:30 AM"
               */
              time: string;
              title: string;
              speaker?: string | null;
              venue?: string | null;
              type?: ('talk' | 'workshop' | 'panel' | 'break' | 'networking') | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'schedule';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlockType".
 */
export interface ContactBlockType {
  heading?: string | null;
  /**
   * Club office or lab address
   */
  address?: string | null;
  email?: string | null;
  phone?: string | null;
  socialLinks?:
    | {
        platform: 'instagram' | 'linkedin' | 'twitter' | 'github' | 'youtube' | 'website';
        url: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Google Maps embed URL (paste the src of the iframe)
   */
  mapEmbedUrl?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'contact';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes".
 */
export interface Vote {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  post: string | Post;
  user: string | User;
  value: number;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  /**
   * The URL path that was viewed
   */
  path: string;
  /**
   * The post that was viewed (null for non-post pages)
   */
  post?: (string | null) | Post;
  /**
   * Slug of the post (for fast lookups without join)
   */
  postSlug?: string | null;
  /**
   * Anonymous session identifier for unique visitor tracking
   */
  sessionId?: string | null;
  /**
   * The referrer URL
   */
  referrer?: string | null;
  userAgent?: string | null;
  /**
   * Country from geo lookup (if available)
   */
  country?: string | null;
  device?: ('desktop' | 'mobile' | 'tablet' | 'unknown') | null;
  browser?: string | null;
  viewedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-logs".
 */
export interface AdminLog {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  action:
    | 'approve_post'
    | 'reject_post'
    | 'delete_post'
    | 'unpublish_post'
    | 'approve_comment'
    | 'reject_comment'
    | 'spam_comment'
    | 'comment_reported'
    | 'role_change'
    | 'user_action'
    | 'content_moderation'
    | 'newsletter_sent'
    | 'newsletter_scheduled'
    | 'newsletter_deleted'
    | 'digest_generated'
    | 'subscriber_imported'
    | 'subscriber_exported'
    | 'subscriber_status_changed'
    | 'template_created'
    | 'template_updated'
    | 'template_published'
    | 'template_unpublished'
    | 'template_deleted'
    | 'event_created'
    | 'event_updated'
    | 'event_synced'
    | 'event_deleted'
    | 'club_created'
    | 'club_updated'
    | 'club_synced'
    | 'club_deleted'
    | 'cache_revalidated';
  resourceType:
    | 'posts'
    | 'comments'
    | 'users'
    | 'media'
    | 'newsletters'
    | 'newsletter-subscribers'
    | 'templates'
    | 'events'
    | 'clubs'
    | 'system';
  /**
   * ID of the affected resource
   */
  resourceId: string;
  /**
   * User who performed the action
   */
  user: string | User;
  /**
   * Additional details about the action
   */
  details?: string | null;
  timestamp: string;
  /**
   * Which module generated this log entry
   */
  module?: ('content' | 'events' | 'clubs' | 'media' | 'newsletter' | 'users' | 'system') | null;
  /**
   * Additional structured data about the action (flexible JSON)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * IP address of the user
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  post: string | Post;
  /**
   * Comment author (optional for anonymous comments)
   */
  author?: (string | null) | User;
  /**
   * Name for anonymous comments
   */
  authorName?: string | null;
  /**
   * Email for anonymous comments (not displayed publicly)
   */
  authorEmail?: string | null;
  content: string;
  status?: ('pending' | 'approved' | 'rejected' | 'spam') | null;
  /**
   * Parent comment (for replies/threading)
   */
  parent?: (string | null) | Comment;
  /**
   * Internal notes for moderators
   */
  moderatorNotes?: string | null;
  /**
   * Editor who moderated this comment
   */
  moderatedBy?: (string | null) | User;
  /**
   * When this comment was moderated
   */
  moderatedAt?: string | null;
  /**
   * User who reported this comment
   */
  reportedBy?: (string | null) | User;
  /**
   * Reason for reporting this comment
   */
  reportReason?: string | null;
  /**
   * When this comment was reported
   */
  reportedAt?: string | null;
  /**
   * IP address of the commenter
   */
  ipAddress?: string | null;
  /**
   * User agent of the commenter
   */
  userAgent?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  title: string;
  /**
   * The post this feedback is related to
   */
  post: string | Post;
  /**
   * The contributor receiving the feedback
   */
  contributor: string | User;
  /**
   * The editor providing the feedback
   */
  editor: string | User;
  /**
   * Type of feedback
   */
  type: 'critical' | 'suggestions' | 'praise' | 'questions';
  status: 'active' | 'resolved' | 'closed';
  messages?:
    | {
        content: string;
        sender: string | User;
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  name: string;
  /**
   * Only published templates are visible to contributors.
   */
  status: 'draft' | 'published';
  /**
   * A short description of what this template is for
   */
  description?: string | null;
  category: 'academic' | 'general' | 'editorial' | 'news';
  /**
   * Maps to contributor content types
   */
  contentType?: ('news' | 'event' | 'literary' | 'media' | 'tutorial' | 'academic') | null;
  audience: 'all' | 'editor_only' | 'contributor_only';
  /**
   * Tiptap-compatible HTML content that will be pre-filled in the editor
   */
  content: string;
  /**
   * Pre-filled title placeholder (user will modify)
   */
  suggestedTitle?: string | null;
  /**
   * Array of tag strings, e.g. ["gcet", "event", "2026"]
   */
  suggestedTags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  icon?:
    | (
        | 'calendar'
        | 'graduation'
        | 'file-text'
        | 'lightbulb'
        | 'users'
        | 'trophy'
        | 'book'
        | 'code'
        | 'megaphone'
        | 'star'
        | 'briefcase'
        | 'list'
      )
    | null;
  usageCount?: number | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email subscribers for the GCET Blog newsletter
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: string;
  /**
   * The institution this subscriber belongs to (optional for public signups)
   */
  institution?: (string | null) | Institution;
  email: string;
  /**
   * Display name (optional)
   */
  name?: string | null;
  /**
   * Subscription status. New subscribers start as "pending" until confirmed.
   */
  status: 'pending' | 'active' | 'unsubscribed' | 'bounced' | 'complained';
  /**
   * How this subscriber was added
   */
  source: 'public_form' | 'user_registration' | 'admin_import' | 'api';
  /**
   * Linked registered user (if applicable)
   */
  user?: (string | null) | User;
  /**
   * Content preferences - only receive digests about these categories
   */
  categories?: (string | Category)[] | null;
  /**
   * How often they want digest emails
   */
  frequency?: ('daily' | 'weekly' | 'monthly') | null;
  /**
   * Unique token for one-click unsubscribe (auto-generated)
   */
  unsubscribeToken?: string | null;
  /**
   * When the subscriber confirmed their email (double opt-in)
   */
  confirmedAt?: string | null;
  /**
   * When the subscriber unsubscribed
   */
  unsubscribedAt?: string | null;
  /**
   * Extensible metadata (UTM source, signup page, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter campaigns - manual compose or auto-generated digests
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  /**
   * Internal campaign name (not shown to subscribers)
   */
  title: string;
  /**
   * Email subject line - seen in inbox
   */
  subject: string;
  /**
   * Inbox preview snippet (appears after subject in most email clients)
   */
  previewText?: string | null;
  type: 'manual' | 'auto_digest';
  /**
   * Digest frequency (only for auto-digest type)
   */
  frequency?: ('daily' | 'weekly' | 'monthly') | null;
  status: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
  /**
   * When to send this campaign
   */
  scheduledFor?: string | null;
  /**
   * Newsletter body (for manual compose)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Posts included in this newsletter (auto-populated for digests)
   */
  posts?: (string | Post)[] | null;
  /**
   * Target specific subscriber segments by category. Leave empty to send to all.
   */
  targetCategories?: (string | Category)[] | null;
  sentAt?: string | null;
  sentBy?: (string | null) | User;
  /**
   * Comma-separated emails for test sends
   */
  testRecipients?: string | null;
  /**
   * Campaign statistics (auto-updated)
   */
  stats?: {
    totalRecipients?: number | null;
    delivered?: number | null;
    opened?: number | null;
    clicked?: number | null;
    bounced?: number | null;
    unsubscribed?: number | null;
  };
  /**
   * React Email template identifier
   */
  templateId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Immutable event log for newsletter analytics (opens, clicks, bounces)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-events".
 */
export interface NewsletterEvent {
  id: string;
  /**
   * Auto-set from your institution
   */
  institution?: (string | null) | Institution;
  newsletter: string | Newsletter;
  /**
   * Null for anonymized/aggregated events
   */
  subscriber?: (string | null) | NewsletterSubscriber;
  type: 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' | 'complained' | 'unsubscribed';
  /**
   * Clicked URL (for click events only)
   */
  url?: string | null;
  /**
   * Browser/email client info
   */
  userAgent?: string | null;
  /**
   * IP address (for geographic context)
   */
  ipAddress?: string | null;
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'newsletter-daily-digest'
          | 'newsletter-weekly-digest'
          | 'newsletter-monthly-digest'
          | 'newsletter-scheduled-send'
          | 'newsletter-stats-rollup'
          | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'newsletter-daily-digest'
        | 'newsletter-weekly-digest'
        | 'newsletter-monthly-digest'
        | 'newsletter-scheduled-send'
        | 'newsletter-stats-rollup'
        | 'schedulePublish'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'institutions';
        value: string | Institution;
      } | null)
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'votes';
        value: string | Vote;
      } | null)
    | ({
        relationTo: 'page-views';
        value: string | PageView;
      } | null)
    | ({
        relationTo: 'admin-logs';
        value: string | AdminLog;
      } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
      } | null)
    | ({
        relationTo: 'feedback';
        value: string | Feedback;
      } | null)
    | ({
        relationTo: 'templates';
        value: string | Template;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: string | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: string | Newsletter;
      } | null)
    | ({
        relationTo: 'newsletter-events';
        value: string | NewsletterEvent;
      } | null)
    | ({
        relationTo: 'events';
        value: string | Event;
      } | null)
    | ({
        relationTo: 'clubs';
        value: string | Club;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "institutions_select".
 */
export interface InstitutionsSelect<T extends boolean = true> {
  name?: T;
  code?: T;
  shortName?: T;
  logo?: T;
  domains?:
    | T
    | {
        hostname?: T;
        purpose?: T;
        scopeId?: T;
        verified?: T;
        id?: T;
      };
  status?: T;
  tier?: T;
  contact?:
    | T
    | {
        email?: T;
        phone?: T;
        website?: T;
        address?: T;
      };
  settings?:
    | T
    | {
        enabledModules?: T;
        maxUsers?: T;
        conoscoInstitutionCode?: T;
        conoscoApiUrl?: T;
      };
  branding?:
    | T
    | {
        primaryColor?: T;
        accentColor?: T;
        tagline?: T;
        favicon?: T;
      };
  headerNavItems?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  footerNavItems?:
    | T
    | {
        label?: T;
        url?: T;
        newTab?: T;
        id?: T;
      };
  footerText?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  institution?: T;
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
        statsBlock?: T | StatsBlockTypeSelect<T>;
        eventsFeed?: T | EventsFeedBlockTypeSelect<T>;
        teamGrid?: T | TeamGridBlockTypeSelect<T>;
        countdown?: T | CountdownBlockTypeSelect<T>;
        galleryPreview?: T | GalleryPreviewBlockTypeSelect<T>;
        sponsors?: T | SponsorsBlockTypeSelect<T>;
        testimonials?: T | TestimonialsBlockTypeSelect<T>;
        schedule?: T | ScheduleBlockTypeSelect<T>;
        contact?: T | ContactBlockTypeSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  club?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "StatsBlockType_select".
 */
export interface StatsBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  layout?: T;
  stats?:
    | T
    | {
        label?: T;
        value?: T;
        icon?: T;
        description?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "EventsFeedBlockType_select".
 */
export interface EventsFeedBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  club?: T;
  limit?: T;
  layout?: T;
  showStatus?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TeamGridBlockType_select".
 */
export interface TeamGridBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  source?: T;
  layout?: T;
  members?:
    | T
    | {
        name?: T;
        role?: T;
        image?: T;
        email?: T;
        linkedIn?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CountdownBlockType_select".
 */
export interface CountdownBlockTypeSelect<T extends boolean = true> {
  eventTitle?: T;
  targetDate?: T;
  description?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "GalleryPreviewBlockType_select".
 */
export interface GalleryPreviewBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  images?:
    | T
    | {
        image?: T;
        caption?: T;
        id?: T;
      };
  layout?: T;
  limit?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "SponsorsBlockType_select".
 */
export interface SponsorsBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  layout?: T;
  sponsors?:
    | T
    | {
        name?: T;
        logo?: T;
        url?: T;
        tier?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TestimonialsBlockType_select".
 */
export interface TestimonialsBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  layout?: T;
  testimonials?:
    | T
    | {
        quote?: T;
        author?: T;
        role?: T;
        image?: T;
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ScheduleBlockType_select".
 */
export interface ScheduleBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  days?:
    | T
    | {
        date?: T;
        title?: T;
        sessions?:
          | T
          | {
              time?: T;
              title?: T;
              speaker?: T;
              venue?: T;
              type?: T;
              id?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContactBlockType_select".
 */
export interface ContactBlockTypeSelect<T extends boolean = true> {
  heading?: T;
  address?: T;
  email?: T;
  phone?: T;
  socialLinks?:
    | T
    | {
        platform?: T;
        url?: T;
        id?: T;
      };
  mapEmbedUrl?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  institution?: T;
  title?: T;
  contentVariant?: T;
  department?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  relatedEvents?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  tags?: T;
  newsletterCandidate?: T;
  featuredFrom?: T;
  featuredUntil?: T;
  voteScore?: T;
  likesCount?: T;
  publishedAt?: T;
  authors?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  editorFeedback?: T;
  reviewStatus?: T;
  submittedForReviewAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  institution?: T;
  alt?: T;
  caption?: T;
  cloudinaryUrl?: T;
  contextType?: T;
  contextId?: T;
  uploadedBy?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  institution?: T;
  title?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  institution?: T;
  role?: T;
  roleAssignments?:
    | T
    | {
        assignedRole?: T;
        scopeType?: T;
        scopeId?: T;
        scopeLabel?: T;
        id?: T;
      };
  bio?: T;
  avatar?: T;
  department?: T;
  year?: T;
  authProvider?: T;
  googleSubId?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        github?: T;
        website?: T;
      };
  newsletterOptIn?: T;
  newsletterFrequency?: T;
  newsletterCategories?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes_select".
 */
export interface VotesSelect<T extends boolean = true> {
  institution?: T;
  post?: T;
  user?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  institution?: T;
  path?: T;
  post?: T;
  postSlug?: T;
  sessionId?: T;
  referrer?: T;
  userAgent?: T;
  country?: T;
  device?: T;
  browser?: T;
  viewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-logs_select".
 */
export interface AdminLogsSelect<T extends boolean = true> {
  institution?: T;
  action?: T;
  resourceType?: T;
  resourceId?: T;
  user?: T;
  details?: T;
  timestamp?: T;
  module?: T;
  metadata?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  institution?: T;
  post?: T;
  author?: T;
  authorName?: T;
  authorEmail?: T;
  content?: T;
  status?: T;
  parent?: T;
  moderatorNotes?: T;
  moderatedBy?: T;
  moderatedAt?: T;
  reportedBy?: T;
  reportReason?: T;
  reportedAt?: T;
  ipAddress?: T;
  userAgent?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  institution?: T;
  title?: T;
  post?: T;
  contributor?: T;
  editor?: T;
  type?: T;
  status?: T;
  messages?:
    | T
    | {
        content?: T;
        sender?: T;
        timestamp?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  institution?: T;
  name?: T;
  status?: T;
  description?: T;
  category?: T;
  contentType?: T;
  audience?: T;
  content?: T;
  suggestedTitle?: T;
  suggestedTags?: T;
  icon?: T;
  usageCount?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  institution?: T;
  email?: T;
  name?: T;
  status?: T;
  source?: T;
  user?: T;
  categories?: T;
  frequency?: T;
  unsubscribeToken?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  institution?: T;
  title?: T;
  subject?: T;
  previewText?: T;
  type?: T;
  frequency?: T;
  status?: T;
  scheduledFor?: T;
  content?: T;
  posts?: T;
  targetCategories?: T;
  sentAt?: T;
  sentBy?: T;
  testRecipients?: T;
  stats?:
    | T
    | {
        totalRecipients?: T;
        delivered?: T;
        opened?: T;
        clicked?: T;
        bounced?: T;
        unsubscribed?: T;
      };
  templateId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-events_select".
 */
export interface NewsletterEventsSelect<T extends boolean = true> {
  institution?: T;
  newsletter?: T;
  subscriber?: T;
  type?: T;
  url?: T;
  userAgent?: T;
  ipAddress?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "events_select".
 */
export interface EventsSelect<T extends boolean = true> {
  institution?: T;
  title?: T;
  organizingClubs?: T;
  createdByClub?: T;
  heroImage?: T;
  editorialDescription?: T;
  eventType?: T;
  department?: T;
  startDate?: T;
  endDate?: T;
  venue?: T;
  manualStatus?: T;
  dataSource?: T;
  registrationUrl?: T;
  externalPlatform?: T;
  externalEventUrl?: T;
  conoscoEventCode?: T;
  lastSyncedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  featured?: T;
  relatedPosts?: T;
  tags?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "clubs_select".
 */
export interface ClubsSelect<T extends boolean = true> {
  institution?: T;
  title?: T;
  heroImage?: T;
  logo?: T;
  editorialDescription?: T;
  classification?: T;
  department?: T;
  manualStatus?: T;
  socialLinks?:
    | T
    | {
        website?: T;
        instagram?: T;
        linkedin?: T;
        twitter?: T;
        github?: T;
      };
  dataSource?: T;
  conoscoClubCode?: T;
  lastSyncedAt?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  theme?:
    | T
    | {
        primaryColor?: T;
        accentColor?: T;
        cardStyle?: T;
        fontPreset?: T;
      };
  featured?: T;
  relatedPosts?: T;
  tags?: T;
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-daily-digest".
 */
export interface TaskNewsletterDailyDigest {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-weekly-digest".
 */
export interface TaskNewsletterWeeklyDigest {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-monthly-digest".
 */
export interface TaskNewsletterMonthlyDigest {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-scheduled-send".
 */
export interface TaskNewsletterScheduledSend {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-stats-rollup".
 */
export interface TaskNewsletterStatsRollup {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null)
      | ({
          relationTo: 'events';
          value: string | Event;
        } | null)
      | ({
          relationTo: 'clubs';
          value: string | Club;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeEmbedBlock".
 */
export interface YouTubeEmbedBlock {
  /**
   * Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)
   */
  videoUrl: string;
  /**
   * Add a caption to describe the video
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtubeEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramEmbedBlock".
 */
export interface InstagramEmbedBlock {
  /**
   * Paste the full Instagram post URL (e.g., https://www.instagram.com/p/ABC123/)
   */
  postUrl: string;
  /**
   * Add a caption to describe the post
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'instagramEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}