/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    pages: Page;
    posts: Post;
    media: Media;
    categories: Category;
    users: User;
    votes: Vote;
    'page-views': PageView;
    'admin-logs': AdminLog;
    comments: Comment;
    feedback: Feedback;
    templates: Template;
    'newsletter-subscribers': NewsletterSubscriber;
    newsletters: Newsletter;
    'newsletter-events': NewsletterEvent;
    'rejection-notifications': RejectionNotification;
    notifications: Notification;
    redirects: Redirect;
    forms: Form;
    'form-submissions': FormSubmission;
    search: Search;
    'payload-kv': PayloadKv;
    'payload-jobs': PayloadJob;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    pages: PagesSelect<false> | PagesSelect<true>;
    posts: PostsSelect<false> | PostsSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    users: UsersSelect<false> | UsersSelect<true>;
    votes: VotesSelect<false> | VotesSelect<true>;
    'page-views': PageViewsSelect<false> | PageViewsSelect<true>;
    'admin-logs': AdminLogsSelect<false> | AdminLogsSelect<true>;
    comments: CommentsSelect<false> | CommentsSelect<true>;
    feedback: FeedbackSelect<false> | FeedbackSelect<true>;
    templates: TemplatesSelect<false> | TemplatesSelect<true>;
    'newsletter-subscribers': NewsletterSubscribersSelect<false> | NewsletterSubscribersSelect<true>;
    newsletters: NewslettersSelect<false> | NewslettersSelect<true>;
    'newsletter-events': NewsletterEventsSelect<false> | NewsletterEventsSelect<true>;
    'rejection-notifications': RejectionNotificationsSelect<false> | RejectionNotificationsSelect<true>;
    notifications: NotificationsSelect<false> | NotificationsSelect<true>;
    redirects: RedirectsSelect<false> | RedirectsSelect<true>;
    forms: FormsSelect<false> | FormsSelect<true>;
    'form-submissions': FormSubmissionsSelect<false> | FormSubmissionsSelect<true>;
    search: SearchSelect<false> | SearchSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-jobs': PayloadJobsSelect<false> | PayloadJobsSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: string;
  };
  fallbackLocale: null;
  globals: {
    header: Header;
    footer: Footer;
    'payload-jobs-stats': PayloadJobsStat;
  };
  globalsSelect: {
    header: HeaderSelect<false> | HeaderSelect<true>;
    footer: FooterSelect<false> | FooterSelect<true>;
    'payload-jobs-stats': PayloadJobsStatsSelect<false> | PayloadJobsStatsSelect<true>;
  };
  locale: null;
  user: User;
  jobs: {
    tasks: {
      'newsletter-daily-digest': TaskNewsletterDailyDigest;
      'newsletter-weekly-digest': TaskNewsletterWeeklyDigest;
      'newsletter-monthly-digest': TaskNewsletterMonthlyDigest;
      'newsletter-scheduled-send': TaskNewsletterScheduledSend;
      'newsletter-stats-rollup': TaskNewsletterStatsRollup;
      schedulePublish: TaskSchedulePublish;
      inline: {
        input: unknown;
        output: unknown;
      };
    };
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: string;
  title: string;
  hero: {
    type: 'none' | 'highImpact' | 'mediumImpact' | 'lowImpact';
    richText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    links?:
      | {
          link: {
            type?: ('reference' | 'custom') | null;
            newTab?: boolean | null;
            reference?:
              | ({
                  relationTo: 'pages';
                  value: string | Page;
                } | null)
              | ({
                  relationTo: 'posts';
                  value: string | Post;
                } | null);
            url?: string | null;
            label: string;
            /**
             * Choose how the link should be rendered.
             */
            appearance?: ('default' | 'outline') | null;
          };
          id?: string | null;
        }[]
      | null;
    media?: (string | null) | Media;
  };
  layout: (CallToActionBlock | ContentBlock | MediaBlock | ArchiveBlock | FormBlock)[];
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  publishedAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts".
 */
export interface Post {
  id: string;
  title: string;
  /**
   * Short summary for cards/previews (max 300 characters)
   */
  excerpt?: string | null;
  /**
   * Recommended: 1920×1080 (16:9). For portraits, keep faces in top 60% of frame. Compress to <500KB.
   */
  heroImage?: (string | null) | Media;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  relatedPosts?: (string | Post)[] | null;
  categories?: (string | Category)[] | null;
  meta?: {
    title?: string | null;
    /**
     * Maximum upload file size: 12MB. Recommended file size for images is <500KB.
     */
    image?: (string | null) | Media;
    description?: string | null;
  };
  /**
   * Free-form tags (comma-separated). E.g: tech, campus, events
   */
  tags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Start date for featuring this post (e.g., event start)
   */
  featuredFrom?: string | null;
  /**
   * End date for featuring this post (e.g., event end)
   */
  featuredUntil?: string | null;
  /**
   * Calculated vote score (upvotes - downvotes)
   */
  voteScore?: number | null;
  /**
   * Total number of upvotes (likes)
   */
  likesCount?: number | null;
  /**
   * Estimated read time in minutes, auto-calculated
   */
  readTime?: number | null;
  /**
   * Total page views (denormalized from PageViews)
   */
  viewCount?: number | null;
  /**
   * Total approved comments (denormalized from Comments)
   */
  commentCount?: number | null;
  /**
   * Net votes (upvotes minus downvotes)
   */
  voteCount?: number | null;
  publishedAt?: string | null;
  authors?: (string | User)[] | null;
  /**
   * When editor last gave feedback
   */
  editorFeedbackAt?: string | null;
  /**
   * Which editor gave the feedback
   */
  feedbackGivenBy?: (string | null) | User;
  /**
   * How many times resubmitted — tracks revision cycles
   */
  submittedForReviewCount?: number | null;
  approvedAt?: string | null;
  approvedBy?: (string | null) | User;
  lastEditedAt?: string | null;
  lastEditedBy?: (string | null) | User;
  /**
   * Soft delete — never hard delete published posts
   */
  isDeleted?: boolean | null;
  deletedAt?: string | null;
  deletedBy?: (string | null) | User;
  populatedAuthors?:
    | {
        id?: string | null;
        name?: string | null;
      }[]
    | null;
  /**
   * Feedback from editor for rejected posts
   */
  editorFeedback?: string | null;
  /**
   * Current review status of the post
   */
  reviewStatus?: ('draft' | 'pending_review' | 'requesting_changes' | 'approved' | 'rejected') | null;
  /**
   * When the post was submitted for review
   */
  submittedForReviewAt?: string | null;
  slug?: string | null;
  slugLock?: boolean | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * 📸 Recommended sizes: Hero 1920×1080 (16:9), Cards 900×600 (3:2), OG 1200×630. Optimize images to <500KB. See IMAGE_GUIDELINES.md for details.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: string;
  /**
   * Required for accessibility and SEO
   */
  alt: string;
  /**
   * Optional caption displayed below image in posts
   */
  caption?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * User who uploaded this media
   */
  uploadedBy?: (string | null) | User;
  /**
   * Cloudinary CDN URL for the uploaded image
   */
  cloudinaryUrl?: string | null;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    square?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    small?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    medium?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    large?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    xlarge?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: string;
  name: string;
  /**
   * Unique username for @mentions
   */
  username?: string | null;
  role?: ('contributor' | 'editor' | 'admin') | null;
  /**
   * Grant admin privileges for user management, logs, and system oversight
   */
  isAdmin?: boolean | null;
  /**
   * Can grant/revoke admin privileges. Protected from deletion.
   */
  canManageAdmins?: boolean | null;
  /**
   * Short bio for author pages (max 500 characters)
   */
  bio?: string | null;
  avatar?: (string | null) | Media;
  /**
   * Department or branch (e.g., CSE, ECE, ME)
   */
  department?: string | null;
  /**
   * Year of study or designation
   */
  year?: string | null;
  lastLoginAt?: string | null;
  loginCount?: number | null;
  lastActiveAt?: string | null;
  /**
   * Number of published posts
   */
  postCount?: number | null;
  commentCount?: number | null;
  /**
   * Deactivate instead of deleting accounts
   */
  isActive?: boolean | null;
  deactivatedAt?: string | null;
  deactivatedBy?: (string | null) | User;
  /**
   * How the user authenticates (managed automatically)
   */
  authProvider?: ('local' | 'google' | 'both') | null;
  /**
   * Google account unique ID (set automatically on Google sign-in)
   */
  googleSubId?: string | null;
  /**
   * Social media profiles
   */
  socialLinks?: {
    /**
     * Twitter/X profile URL
     */
    twitter?: string | null;
    /**
     * LinkedIn profile URL
     */
    linkedin?: string | null;
    /**
     * GitHub profile URL
     */
    github?: string | null;
    /**
     * Personal website URL
     */
    website?: string | null;
  };
  /**
   * Opt-in to receive the GCET Blog newsletter
   */
  newsletterOptIn?: boolean | null;
  /**
   * How often you want to receive newsletters
   */
  newsletterFrequency?: ('daily' | 'weekly' | 'monthly') | null;
  /**
   * Only receive newsletters about these categories (leave empty for all)
   */
  newsletterCategories?: (string | Category)[] | null;
  /**
   * Email notification preferences
   */
  emailNotifications?: {
    /**
     * Notify when your post is approved
     */
    onPostApproved?: boolean | null;
    /**
     * Notify when your post is rejected
     */
    onPostRejected?: boolean | null;
    /**
     * Notify when editor provides feedback
     */
    onEditorFeedback?: boolean | null;
    /**
     * Notify when someone replies to your comment
     */
    onCommentReply?: boolean | null;
    /**
     * Receive newsletter emails
     */
    newsletter?: boolean | null;
  };
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: string;
  title: string;
  /**
   * Category description for SEO and category pages
   */
  description?: string | null;
  /**
   * Number of posts in this category (denormalized)
   */
  postCount?: number | null;
  /**
   * Hex color for category badge, e.g. #3B82F6
   */
  color?: string | null;
  /**
   * Inactive categories are hidden from public view
   */
  isActive?: boolean | null;
  /**
   * Manual sort order for navigation display (lower numbers first)
   */
  order?: number | null;
  slug?: string | null;
  slugLock?: boolean | null;
  parent?: (string | null) | Category;
  breadcrumbs?:
    | {
        doc?: (string | null) | Category;
        url?: string | null;
        label?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock".
 */
export interface CallToActionBlock {
  richText?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  links?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'cta';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock".
 */
export interface ContentBlock {
  columns?:
    | {
        size?: ('oneThird' | 'half' | 'twoThirds' | 'full') | null;
        richText?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        enableLink?: boolean | null;
        link?: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
          /**
           * Choose how the link should be rendered.
           */
          appearance?: ('default' | 'outline') | null;
        };
        id?: string | null;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'content';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock".
 */
export interface MediaBlock {
  media: string | Media;
  id?: string | null;
  blockName?: string | null;
  blockType: 'mediaBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock".
 */
export interface ArchiveBlock {
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  populateBy?: ('collection' | 'selection') | null;
  relationTo?: 'posts' | null;
  categories?: (string | Category)[] | null;
  limit?: number | null;
  selectedDocs?:
    | {
        relationTo: 'posts';
        value: string | Post;
      }[]
    | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'archive';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock".
 */
export interface FormBlock {
  form: string | Form;
  enableIntro?: boolean | null;
  introContent?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'formBlock';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms".
 */
export interface Form {
  id: string;
  title: string;
  fields?:
    | (
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            defaultValue?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'checkbox';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'country';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'email';
          }
        | {
            message?: {
              root: {
                type: string;
                children: {
                  type: any;
                  version: number;
                  [k: string]: unknown;
                }[];
                direction: ('ltr' | 'rtl') | null;
                format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
                indent: number;
                version: number;
              };
              [k: string]: unknown;
            } | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'message';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'number';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            placeholder?: string | null;
            options?:
              | {
                  label: string;
                  value: string;
                  id?: string | null;
                }[]
              | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'select';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'state';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'text';
          }
        | {
            name: string;
            label?: string | null;
            width?: number | null;
            defaultValue?: string | null;
            required?: boolean | null;
            id?: string | null;
            blockName?: string | null;
            blockType: 'textarea';
          }
      )[]
    | null;
  submitButtonLabel?: string | null;
  /**
   * Choose whether to display an on-page message or redirect to a different page after they submit the form.
   */
  confirmationType?: ('message' | 'redirect') | null;
  confirmationMessage?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  redirect?: {
    url: string;
  };
  /**
   * Send custom emails when the form submits. Use comma separated lists to send the same email to multiple recipients. To reference a value from this form, wrap that field's name with double curly brackets, i.e. {{firstName}}. You can use a wildcard {{*}} to output all data and {{*:table}} to format it as an HTML table in the email.
   */
  emails?:
    | {
        emailTo?: string | null;
        cc?: string | null;
        bcc?: string | null;
        replyTo?: string | null;
        emailFrom?: string | null;
        subject: string;
        /**
         * Enter the message that should be sent in this email.
         */
        message?: {
          root: {
            type: string;
            children: {
              type: any;
              version: number;
              [k: string]: unknown;
            }[];
            direction: ('ltr' | 'rtl') | null;
            format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
            indent: number;
            version: number;
          };
          [k: string]: unknown;
        } | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes".
 */
export interface Vote {
  id: string;
  post: string | Post;
  user: string | User;
  value: number;
  /**
   * Previous vote type before change (for tracking)
   */
  previousVoteType?: ('upvote' | 'downvote') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views".
 */
export interface PageView {
  id: string;
  /**
   * The URL path that was viewed
   */
  path: string;
  /**
   * The post that was viewed (null for non-post pages)
   */
  post?: (string | null) | Post;
  /**
   * Slug of the post (for fast lookups without join)
   */
  postSlug?: string | null;
  /**
   * Anonymous session identifier for unique visitor tracking
   */
  sessionId?: string | null;
  /**
   * The referrer URL
   */
  referrer?: string | null;
  userAgent?: string | null;
  /**
   * Country from geo lookup (if available)
   */
  country?: string | null;
  device?: ('desktop' | 'mobile' | 'tablet' | 'unknown') | null;
  browser?: string | null;
  /**
   * Hashed IP for privacy-compliant tracking
   */
  ipHash?: string | null;
  /**
   * Seconds the user spent on the page
   */
  readDuration?: number | null;
  /**
   * How far the user scrolled (0-100)
   */
  readPercentage?: number | null;
  /**
   * Whether the viewer was logged in
   */
  isAuthenticated?: boolean | null;
  viewedAt: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-logs".
 */
export interface AdminLog {
  id: string;
  action:
    | 'approve_post'
    | 'reject_post'
    | 'delete_post'
    | 'unpublish_post'
    | 'approve_comment'
    | 'reject_comment'
    | 'spam_comment'
    | 'comment_reported'
    | 'role_change'
    | 'user_action'
    | 'content_moderation'
    | 'newsletter_sent'
    | 'newsletter_scheduled'
    | 'newsletter_deleted'
    | 'digest_generated'
    | 'subscriber_imported'
    | 'subscriber_exported'
    | 'subscriber_status_changed'
    | 'template_created'
    | 'template_updated'
    | 'template_published'
    | 'template_unpublished'
    | 'template_deleted';
  resourceType: 'posts' | 'comments' | 'users' | 'media' | 'newsletters' | 'newsletter-subscribers' | 'templates';
  /**
   * ID of the affected resource
   */
  resourceId: string;
  /**
   * User who performed the action
   */
  user: string | User;
  /**
   * Additional details about the action
   */
  details?: string | null;
  timestamp: string;
  /**
   * IP address of the user
   */
  ipAddress?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments".
 */
export interface Comment {
  id: string;
  post: string | Post;
  /**
   * Comment author (optional for anonymous comments)
   */
  author?: (string | null) | User;
  /**
   * Name for anonymous comments
   */
  authorName?: string | null;
  /**
   * Email for anonymous comments (not displayed publicly)
   */
  authorEmail?: string | null;
  content: string;
  status?: ('pending' | 'approved' | 'rejected' | 'spam') | null;
  /**
   * Parent comment (for replies/threading)
   */
  parent?: (string | null) | Comment;
  /**
   * Internal notes for moderators
   */
  moderatorNotes?: string | null;
  /**
   * Editor who moderated this comment
   */
  moderatedBy?: (string | null) | User;
  /**
   * When this comment was moderated
   */
  moderatedAt?: string | null;
  /**
   * Type of spam (when marked as spam)
   */
  spamType?: ('commercial' | 'malicious' | 'off-topic' | 'abusive' | 'bot-generated') | null;
  /**
   * Reason for rejecting this comment
   */
  rejectionReason?:
    | ('violates guidelines' | 'spam' | 'off-topic' | 'inappropriate language' | 'duplicate' | 'other')
    | null;
  /**
   * Custom rejection reason (when "other" is selected)
   */
  rejectionReasonCustom?: string | null;
  /**
   * Indicates if comment content was modified by an editor
   */
  contentModified?: boolean | null;
  /**
   * History of content modifications
   */
  revisionHistory?:
    | {
        originalContent: string;
        modifiedBy: string | User;
        modifiedAt: string;
        reason: string;
        id?: string | null;
      }[]
    | null;
  /**
   * IP address of the commenter
   */
  ipAddress?: string | null;
  /**
   * User agent of the commenter
   */
  userAgent?: string | null;
  /**
   * User who reported this comment
   */
  reportedBy?: (string | null) | User;
  /**
   * Reason for reporting this comment
   */
  reportReason?: string | null;
  /**
   * When this comment was reported
   */
  reportedAt?: string | null;
  /**
   * When the report was resolved
   */
  reportResolvedAt?: string | null;
  /**
   * Action taken to resolve the report
   */
  reportResolutionAction?: ('no-action' | 'approved' | 'rejected' | 'spam') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback".
 */
export interface Feedback {
  id: string;
  title: string;
  /**
   * The post this feedback is related to
   */
  post: string | Post;
  /**
   * The contributor receiving the feedback
   */
  contributor: string | User;
  /**
   * The editor providing the feedback
   */
  editor: string | User;
  /**
   * Type of feedback
   */
  type: 'critical' | 'suggestions' | 'praise' | 'questions';
  status: 'active' | 'resolved' | 'closed';
  messages?:
    | {
        content: string;
        sender: string | User;
        timestamp?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates".
 */
export interface Template {
  id: string;
  name: string;
  /**
   * Only published templates are visible to contributors.
   */
  status: 'draft' | 'published';
  /**
   * A short description of what this template is for
   */
  description?: string | null;
  category: 'academic' | 'general' | 'editorial' | 'news';
  /**
   * Maps to contributor content types
   */
  contentType?: ('news' | 'event' | 'literary' | 'media' | 'tutorial' | 'academic') | null;
  audience: 'all' | 'editor_only' | 'contributor_only';
  /**
   * Tiptap-compatible HTML content that will be pre-filled in the editor
   */
  content: string;
  /**
   * Pre-filled title placeholder (user will modify)
   */
  suggestedTitle?: string | null;
  /**
   * Array of tag strings, e.g. ["gcet", "event", "2026"]
   */
  suggestedTags?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  icon?:
    | (
        | 'calendar'
        | 'graduation'
        | 'file-text'
        | 'lightbulb'
        | 'users'
        | 'trophy'
        | 'book'
        | 'code'
        | 'megaphone'
        | 'star'
        | 'briefcase'
        | 'list'
      )
    | null;
  usageCount?: number | null;
  createdBy?: (string | null) | User;
  updatedAt: string;
  createdAt: string;
}
/**
 * Email subscribers for the GCET Blog newsletter
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers".
 */
export interface NewsletterSubscriber {
  id: string;
  email: string;
  /**
   * Display name (optional)
   */
  name?: string | null;
  /**
   * Subscription status. New subscribers start as "pending" until confirmed.
   */
  status: 'pending' | 'active' | 'unsubscribed' | 'bounced' | 'complained';
  /**
   * How this subscriber was added
   */
  source: 'public_form' | 'user_registration' | 'admin_import' | 'api';
  /**
   * Linked registered user (if applicable)
   */
  user?: (string | null) | User;
  /**
   * Content preferences - only receive digests about these categories
   */
  categories?: (string | Category)[] | null;
  /**
   * How often they want digest emails
   */
  frequency?: ('daily' | 'weekly' | 'monthly') | null;
  /**
   * Unique token for one-click unsubscribe (auto-generated)
   */
  unsubscribeToken?: string | null;
  /**
   * When the subscriber confirmed their email (double opt-in)
   */
  confirmedAt?: string | null;
  /**
   * When the subscriber unsubscribed
   */
  unsubscribedAt?: string | null;
  /**
   * Extensible metadata (UTM source, signup page, etc.)
   */
  metadata?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Newsletter campaigns - manual compose or auto-generated digests
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters".
 */
export interface Newsletter {
  id: string;
  /**
   * Internal campaign name (not shown to subscribers)
   */
  title: string;
  /**
   * Email subject line - seen in inbox
   */
  subject: string;
  /**
   * Inbox preview snippet (appears after subject in most email clients)
   */
  previewText?: string | null;
  type: 'manual' | 'auto_digest';
  /**
   * Digest frequency (only for auto-digest type)
   */
  frequency?: ('daily' | 'weekly' | 'monthly') | null;
  status: 'draft' | 'scheduled' | 'sending' | 'sent' | 'failed';
  /**
   * When to send this campaign
   */
  scheduledFor?: string | null;
  /**
   * Newsletter body (for manual compose)
   */
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Posts included in this newsletter (auto-populated for digests)
   */
  posts?: (string | Post)[] | null;
  /**
   * Target specific subscriber segments by category. Leave empty to send to all.
   */
  targetCategories?: (string | Category)[] | null;
  sentAt?: string | null;
  sentBy?: (string | null) | User;
  /**
   * Comma-separated emails for test sends
   */
  testRecipients?: string | null;
  /**
   * Campaign statistics (auto-updated)
   */
  stats?: {
    totalRecipients?: number | null;
    delivered?: number | null;
    opened?: number | null;
    clicked?: number | null;
    bounced?: number | null;
    unsubscribed?: number | null;
  };
  /**
   * React Email template identifier
   */
  templateId?: string | null;
  updatedAt: string;
  createdAt: string;
  _status?: ('draft' | 'published') | null;
}
/**
 * Immutable event log for newsletter analytics (opens, clicks, bounces)
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-events".
 */
export interface NewsletterEvent {
  id: string;
  newsletter: string | Newsletter;
  /**
   * Null for anonymized/aggregated events
   */
  subscriber?: (string | null) | NewsletterSubscriber;
  type: 'sent' | 'delivered' | 'opened' | 'clicked' | 'bounced' | 'complained' | 'unsubscribed';
  /**
   * Clicked URL (for click events only)
   */
  url?: string | null;
  /**
   * Browser/email client info
   */
  userAgent?: string | null;
  /**
   * IP address (for geographic context)
   */
  ipAddress?: string | null;
  timestamp: string;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rejection-notifications".
 */
export interface RejectionNotification {
  id: string;
  /**
   * Title of the rejected post
   */
  postTitle: string;
  /**
   * The contributor whose post was rejected
   */
  contributor: string | User;
  /**
   * The editor who rejected the post
   */
  rejectedBy: string | User;
  /**
   * Reason for rejection
   */
  reason: string;
  /**
   * ID of the original post (for reference)
   */
  originalPostId: string;
  /**
   * Whether the contributor has read this notification
   */
  isRead?: boolean | null;
  /**
   * When the notification was read
   */
  readAt?: string | null;
  /**
   * Stored because post is deleted
   */
  postSlug?: string | null;
  /**
   * First 200 chars stored for context
   */
  postExcerpt?: string | null;
  /**
   * How many revision cycles before rejection
   */
  submittedForReviewCount?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications".
 */
export interface Notification {
  id: string;
  recipient: string | User;
  type:
    | 'post_approved'
    | 'post_rejected'
    | 'feedback_received'
    | 'comment_replied'
    | 'post_commented'
    | 'comment_flagged'
    | 'role_changed';
  title: string;
  message?: string | null;
  /**
   * URL to navigate to when notification is clicked
   */
  link?: string | null;
  relatedPost?: (string | null) | Post;
  relatedComment?: (string | null) | Comment;
  /**
   * The person whose action caused this notification
   */
  triggeredBy?: (string | null) | User;
  isRead?: boolean | null;
  readAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects".
 */
export interface Redirect {
  id: string;
  /**
   * You will need to rebuild the website when changing this field.
   */
  from: string;
  to?: {
    type?: ('reference' | 'custom') | null;
    reference?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    url?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions".
 */
export interface FormSubmission {
  id: string;
  form: string | Form;
  submissionData?:
    | {
        field: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This is a collection of automatically created search results. These results are used by the global site search and will be updated automatically as documents in the CMS are created or updated.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search".
 */
export interface Search {
  id: string;
  title?: string | null;
  priority?: number | null;
  doc: {
    relationTo: 'posts';
    value: string | Post;
  };
  slug?: string | null;
  meta?: {
    title?: string | null;
    description?: string | null;
    image?: (string | null) | Media;
  };
  categories?:
    | {
        relationTo?: string | null;
        categoryID?: string | null;
        title?: string | null;
        id?: string | null;
      }[]
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: string;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs".
 */
export interface PayloadJob {
  id: string;
  /**
   * Input data provided to the job
   */
  input?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  taskStatus?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  completedAt?: string | null;
  totalTried?: number | null;
  /**
   * If hasError is true this job will not be retried
   */
  hasError?: boolean | null;
  /**
   * If hasError is true, this is the error that caused it
   */
  error?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  /**
   * Task execution log
   */
  log?:
    | {
        executedAt: string;
        completedAt: string;
        taskSlug:
          | 'inline'
          | 'newsletter-daily-digest'
          | 'newsletter-weekly-digest'
          | 'newsletter-monthly-digest'
          | 'newsletter-scheduled-send'
          | 'newsletter-stats-rollup'
          | 'schedulePublish';
        taskID: string;
        input?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        output?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        state: 'failed' | 'succeeded';
        error?:
          | {
              [k: string]: unknown;
            }
          | unknown[]
          | string
          | number
          | boolean
          | null;
        id?: string | null;
      }[]
    | null;
  taskSlug?:
    | (
        | 'inline'
        | 'newsletter-daily-digest'
        | 'newsletter-weekly-digest'
        | 'newsletter-monthly-digest'
        | 'newsletter-scheduled-send'
        | 'newsletter-stats-rollup'
        | 'schedulePublish'
      )
    | null;
  queue?: string | null;
  waitUntil?: string | null;
  processing?: boolean | null;
  meta?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: string;
  document?:
    | ({
        relationTo: 'pages';
        value: string | Page;
      } | null)
    | ({
        relationTo: 'posts';
        value: string | Post;
      } | null)
    | ({
        relationTo: 'media';
        value: string | Media;
      } | null)
    | ({
        relationTo: 'categories';
        value: string | Category;
      } | null)
    | ({
        relationTo: 'users';
        value: string | User;
      } | null)
    | ({
        relationTo: 'votes';
        value: string | Vote;
      } | null)
    | ({
        relationTo: 'page-views';
        value: string | PageView;
      } | null)
    | ({
        relationTo: 'admin-logs';
        value: string | AdminLog;
      } | null)
    | ({
        relationTo: 'comments';
        value: string | Comment;
      } | null)
    | ({
        relationTo: 'feedback';
        value: string | Feedback;
      } | null)
    | ({
        relationTo: 'templates';
        value: string | Template;
      } | null)
    | ({
        relationTo: 'newsletter-subscribers';
        value: string | NewsletterSubscriber;
      } | null)
    | ({
        relationTo: 'newsletters';
        value: string | Newsletter;
      } | null)
    | ({
        relationTo: 'newsletter-events';
        value: string | NewsletterEvent;
      } | null)
    | ({
        relationTo: 'rejection-notifications';
        value: string | RejectionNotification;
      } | null)
    | ({
        relationTo: 'notifications';
        value: string | Notification;
      } | null)
    | ({
        relationTo: 'redirects';
        value: string | Redirect;
      } | null)
    | ({
        relationTo: 'forms';
        value: string | Form;
      } | null)
    | ({
        relationTo: 'form-submissions';
        value: string | FormSubmission;
      } | null)
    | ({
        relationTo: 'search';
        value: string | Search;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  hero?:
    | T
    | {
        type?: T;
        richText?: T;
        links?:
          | T
          | {
              link?:
                | T
                | {
                    type?: T;
                    newTab?: T;
                    reference?: T;
                    url?: T;
                    label?: T;
                    appearance?: T;
                  };
              id?: T;
            };
        media?: T;
      };
  layout?:
    | T
    | {
        cta?: T | CallToActionBlockSelect<T>;
        content?: T | ContentBlockSelect<T>;
        mediaBlock?: T | MediaBlockSelect<T>;
        archive?: T | ArchiveBlockSelect<T>;
        formBlock?: T | FormBlockSelect<T>;
      };
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  publishedAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CallToActionBlock_select".
 */
export interface CallToActionBlockSelect<T extends boolean = true> {
  richText?: T;
  links?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ContentBlock_select".
 */
export interface ContentBlockSelect<T extends boolean = true> {
  columns?:
    | T
    | {
        size?: T;
        richText?: T;
        enableLink?: T;
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
              appearance?: T;
            };
        id?: T;
      };
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "MediaBlock_select".
 */
export interface MediaBlockSelect<T extends boolean = true> {
  media?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ArchiveBlock_select".
 */
export interface ArchiveBlockSelect<T extends boolean = true> {
  introContent?: T;
  populateBy?: T;
  relationTo?: T;
  categories?: T;
  limit?: T;
  selectedDocs?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "FormBlock_select".
 */
export interface FormBlockSelect<T extends boolean = true> {
  form?: T;
  enableIntro?: T;
  introContent?: T;
  id?: T;
  blockName?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "posts_select".
 */
export interface PostsSelect<T extends boolean = true> {
  title?: T;
  excerpt?: T;
  heroImage?: T;
  content?: T;
  relatedPosts?: T;
  categories?: T;
  meta?:
    | T
    | {
        title?: T;
        image?: T;
        description?: T;
      };
  tags?: T;
  featuredFrom?: T;
  featuredUntil?: T;
  voteScore?: T;
  likesCount?: T;
  readTime?: T;
  viewCount?: T;
  commentCount?: T;
  voteCount?: T;
  publishedAt?: T;
  authors?: T;
  editorFeedbackAt?: T;
  feedbackGivenBy?: T;
  submittedForReviewCount?: T;
  approvedAt?: T;
  approvedBy?: T;
  lastEditedAt?: T;
  lastEditedBy?: T;
  isDeleted?: T;
  deletedAt?: T;
  deletedBy?: T;
  populatedAuthors?:
    | T
    | {
        id?: T;
        name?: T;
      };
  editorFeedback?: T;
  reviewStatus?: T;
  submittedForReviewAt?: T;
  slug?: T;
  slugLock?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  caption?: T;
  uploadedBy?: T;
  cloudinaryUrl?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        square?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        small?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        medium?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        large?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        xlarge?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  title?: T;
  description?: T;
  postCount?: T;
  color?: T;
  isActive?: T;
  order?: T;
  slug?: T;
  slugLock?: T;
  parent?: T;
  breadcrumbs?:
    | T
    | {
        doc?: T;
        url?: T;
        label?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  username?: T;
  role?: T;
  isAdmin?: T;
  canManageAdmins?: T;
  bio?: T;
  avatar?: T;
  department?: T;
  year?: T;
  lastLoginAt?: T;
  loginCount?: T;
  lastActiveAt?: T;
  postCount?: T;
  commentCount?: T;
  isActive?: T;
  deactivatedAt?: T;
  deactivatedBy?: T;
  authProvider?: T;
  googleSubId?: T;
  socialLinks?:
    | T
    | {
        twitter?: T;
        linkedin?: T;
        github?: T;
        website?: T;
      };
  newsletterOptIn?: T;
  newsletterFrequency?: T;
  newsletterCategories?: T;
  emailNotifications?:
    | T
    | {
        onPostApproved?: T;
        onPostRejected?: T;
        onEditorFeedback?: T;
        onCommentReply?: T;
        newsletter?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "votes_select".
 */
export interface VotesSelect<T extends boolean = true> {
  post?: T;
  user?: T;
  value?: T;
  previousVoteType?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "page-views_select".
 */
export interface PageViewsSelect<T extends boolean = true> {
  path?: T;
  post?: T;
  postSlug?: T;
  sessionId?: T;
  referrer?: T;
  userAgent?: T;
  country?: T;
  device?: T;
  browser?: T;
  ipHash?: T;
  readDuration?: T;
  readPercentage?: T;
  isAuthenticated?: T;
  viewedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "admin-logs_select".
 */
export interface AdminLogsSelect<T extends boolean = true> {
  action?: T;
  resourceType?: T;
  resourceId?: T;
  user?: T;
  details?: T;
  timestamp?: T;
  ipAddress?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comments_select".
 */
export interface CommentsSelect<T extends boolean = true> {
  post?: T;
  author?: T;
  authorName?: T;
  authorEmail?: T;
  content?: T;
  status?: T;
  parent?: T;
  moderatorNotes?: T;
  moderatedBy?: T;
  moderatedAt?: T;
  spamType?: T;
  rejectionReason?: T;
  rejectionReasonCustom?: T;
  contentModified?: T;
  revisionHistory?:
    | T
    | {
        originalContent?: T;
        modifiedBy?: T;
        modifiedAt?: T;
        reason?: T;
        id?: T;
      };
  ipAddress?: T;
  userAgent?: T;
  reportedBy?: T;
  reportReason?: T;
  reportedAt?: T;
  reportResolvedAt?: T;
  reportResolutionAction?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "feedback_select".
 */
export interface FeedbackSelect<T extends boolean = true> {
  title?: T;
  post?: T;
  contributor?: T;
  editor?: T;
  type?: T;
  status?: T;
  messages?:
    | T
    | {
        content?: T;
        sender?: T;
        timestamp?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "templates_select".
 */
export interface TemplatesSelect<T extends boolean = true> {
  name?: T;
  status?: T;
  description?: T;
  category?: T;
  contentType?: T;
  audience?: T;
  content?: T;
  suggestedTitle?: T;
  suggestedTags?: T;
  icon?: T;
  usageCount?: T;
  createdBy?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-subscribers_select".
 */
export interface NewsletterSubscribersSelect<T extends boolean = true> {
  email?: T;
  name?: T;
  status?: T;
  source?: T;
  user?: T;
  categories?: T;
  frequency?: T;
  unsubscribeToken?: T;
  confirmedAt?: T;
  unsubscribedAt?: T;
  metadata?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletters_select".
 */
export interface NewslettersSelect<T extends boolean = true> {
  title?: T;
  subject?: T;
  previewText?: T;
  type?: T;
  frequency?: T;
  status?: T;
  scheduledFor?: T;
  content?: T;
  posts?: T;
  targetCategories?: T;
  sentAt?: T;
  sentBy?: T;
  testRecipients?: T;
  stats?:
    | T
    | {
        totalRecipients?: T;
        delivered?: T;
        opened?: T;
        clicked?: T;
        bounced?: T;
        unsubscribed?: T;
      };
  templateId?: T;
  updatedAt?: T;
  createdAt?: T;
  _status?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "newsletter-events_select".
 */
export interface NewsletterEventsSelect<T extends boolean = true> {
  newsletter?: T;
  subscriber?: T;
  type?: T;
  url?: T;
  userAgent?: T;
  ipAddress?: T;
  timestamp?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rejection-notifications_select".
 */
export interface RejectionNotificationsSelect<T extends boolean = true> {
  postTitle?: T;
  contributor?: T;
  rejectedBy?: T;
  reason?: T;
  originalPostId?: T;
  isRead?: T;
  readAt?: T;
  postSlug?: T;
  postExcerpt?: T;
  submittedForReviewCount?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "notifications_select".
 */
export interface NotificationsSelect<T extends boolean = true> {
  recipient?: T;
  type?: T;
  title?: T;
  message?: T;
  link?: T;
  relatedPost?: T;
  relatedComment?: T;
  triggeredBy?: T;
  isRead?: T;
  readAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "redirects_select".
 */
export interface RedirectsSelect<T extends boolean = true> {
  from?: T;
  to?:
    | T
    | {
        type?: T;
        reference?: T;
        url?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "forms_select".
 */
export interface FormsSelect<T extends boolean = true> {
  title?: T;
  fields?:
    | T
    | {
        checkbox?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              defaultValue?: T;
              id?: T;
              blockName?: T;
            };
        country?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        email?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        message?:
          | T
          | {
              message?: T;
              id?: T;
              blockName?: T;
            };
        number?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        select?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              placeholder?: T;
              options?:
                | T
                | {
                    label?: T;
                    value?: T;
                    id?: T;
                  };
              required?: T;
              id?: T;
              blockName?: T;
            };
        state?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        text?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
        textarea?:
          | T
          | {
              name?: T;
              label?: T;
              width?: T;
              defaultValue?: T;
              required?: T;
              id?: T;
              blockName?: T;
            };
      };
  submitButtonLabel?: T;
  confirmationType?: T;
  confirmationMessage?: T;
  redirect?:
    | T
    | {
        url?: T;
      };
  emails?:
    | T
    | {
        emailTo?: T;
        cc?: T;
        bcc?: T;
        replyTo?: T;
        emailFrom?: T;
        subject?: T;
        message?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "form-submissions_select".
 */
export interface FormSubmissionsSelect<T extends boolean = true> {
  form?: T;
  submissionData?:
    | T
    | {
        field?: T;
        value?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "search_select".
 */
export interface SearchSelect<T extends boolean = true> {
  title?: T;
  priority?: T;
  doc?: T;
  slug?: T;
  meta?:
    | T
    | {
        title?: T;
        description?: T;
        image?: T;
      };
  categories?:
    | T
    | {
        relationTo?: T;
        categoryID?: T;
        title?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs_select".
 */
export interface PayloadJobsSelect<T extends boolean = true> {
  input?: T;
  taskStatus?: T;
  completedAt?: T;
  totalTried?: T;
  hasError?: T;
  error?: T;
  log?:
    | T
    | {
        executedAt?: T;
        completedAt?: T;
        taskSlug?: T;
        taskID?: T;
        input?: T;
        output?: T;
        state?: T;
        error?: T;
        id?: T;
      };
  taskSlug?: T;
  queue?: T;
  waitUntil?: T;
  processing?: T;
  meta?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header".
 */
export interface Header {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer".
 */
export interface Footer {
  id: string;
  navItems?:
    | {
        link: {
          type?: ('reference' | 'custom') | null;
          newTab?: boolean | null;
          reference?:
            | ({
                relationTo: 'pages';
                value: string | Page;
              } | null)
            | ({
                relationTo: 'posts';
                value: string | Post;
              } | null);
          url?: string | null;
          label: string;
        };
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats".
 */
export interface PayloadJobsStat {
  id: string;
  stats?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "header_select".
 */
export interface HeaderSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "footer_select".
 */
export interface FooterSelect<T extends boolean = true> {
  navItems?:
    | T
    | {
        link?:
          | T
          | {
              type?: T;
              newTab?: T;
              reference?: T;
              url?: T;
              label?: T;
            };
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-jobs-stats_select".
 */
export interface PayloadJobsStatsSelect<T extends boolean = true> {
  stats?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-daily-digest".
 */
export interface TaskNewsletterDailyDigest {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-weekly-digest".
 */
export interface TaskNewsletterWeeklyDigest {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-monthly-digest".
 */
export interface TaskNewsletterMonthlyDigest {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-scheduled-send".
 */
export interface TaskNewsletterScheduledSend {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskNewsletter-stats-rollup".
 */
export interface TaskNewsletterStatsRollup {
  input?: unknown;
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "TaskSchedulePublish".
 */
export interface TaskSchedulePublish {
  input: {
    type?: ('publish' | 'unpublish') | null;
    locale?: string | null;
    doc?:
      | ({
          relationTo: 'pages';
          value: string | Page;
        } | null)
      | ({
          relationTo: 'posts';
          value: string | Post;
        } | null);
    global?: string | null;
    user?: (string | null) | User;
  };
  output?: unknown;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "BannerBlock".
 */
export interface BannerBlock {
  style: 'info' | 'warning' | 'error' | 'success';
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  id?: string | null;
  blockName?: string | null;
  blockType: 'banner';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "CodeBlock".
 */
export interface CodeBlock {
  language?: ('typescript' | 'javascript' | 'css') | null;
  code: string;
  id?: string | null;
  blockName?: string | null;
  blockType: 'code';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "YouTubeEmbedBlock".
 */
export interface YouTubeEmbedBlock {
  /**
   * Paste the full YouTube URL (e.g., https://www.youtube.com/watch?v=dQw4w9WgXcQ)
   */
  videoUrl: string;
  /**
   * Add a caption to describe the video
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'youtubeEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "InstagramEmbedBlock".
 */
export interface InstagramEmbedBlock {
  /**
   * Paste the full Instagram post URL (e.g., https://www.instagram.com/p/ABC123/)
   */
  postUrl: string;
  /**
   * Add a caption to describe the post
   */
  caption?: string | null;
  id?: string | null;
  blockName?: string | null;
  blockType: 'instagramEmbed';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}